---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "openstack-exporter.fullname" . }}
  labels:
{{- include "openstack-exporter.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{- include "openstack-exporter.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{- include "openstack-exporter.labels" . | indent 8 }}
    spec:
      containers:
      - name: openstack-exporter
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --endpoint-type
        - {{ .Values.endpoint_type }}
{{- if .Values.multicloud.enabled }}
        - --multi-cloud
{{- else }}
        - {{ .Values.cloud }}
{{- end }}
        {{- with .Values.extraArgs }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: openstack-config
          mountPath: /etc/openstack
        {{- if .Values.extraVolumeMounts }}
          {{- toYaml .Values.extraVolumeMounts | nindent 8 }}
        {{- end }}
        ports:
        - name: metrics
          containerPort: 9180
        env:
        {{- range $name, $value := .Values.extraEnvs }}
        - name: {{ quote $name }}
          value: {{ quote $value }}
        {{- end }}
      volumes:
      - name: openstack-config
        secret:
          secretName: openstack-config
      {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}
    {{- with .Values.hostAliases }}
      hostAliases:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
